{
  "x-generator": "NSwag v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "Charge Amps External REST API5",
    "description": "\n<p>\n    Charge Amps external api is intended for integration purposes. Both private and enterprise users can use it.\n    Besides the functionality described below the api provides the following callbacks/web hooks:\n</p>\n<ul>\n    <li>POST chargepoints/{chargepointid}/boot, returns <a href='#model-ChargePoint'>ChargePoint</a></li>\n    <li>POST chargepoints/{chargepointid}/heartbeat, returns <a href='#model-ChargePointStatus'>ChargePointStatus</a></li>\n    <li>POST char[...]",
    "termsOfService": "https://chargeamps.com/terms-of-service/",
    "contact": {
      "name": "Charge Amps Support",
      "url": "https://chargeamps.com/support"
    },
    "version": "v5"
  },
  "servers": [
    {
      "url": "https://eapi.charge.space"
    }
  ],
  "paths": {
    "/api/v5/auth/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Authenticates an enterprise or private user for using the api. A Bearer token is returned if the login is successful. A refresh token\nis also returned which can be used to get a new bearer token in case the former one has expired.\nNote that an api key also needs to provided in the header.",
        "operationId": "Auth_Login"
      }
    },
    "/api/v5/auth/refreshtoken": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Gets a new bearer token (and a refresh token) if the former one has expired.\nNote, the expired token with the refresh token has to be sent in on order to get new ones",
        "operationId": "Auth_RefreshTokens"
      }
    },
    "/api/v5/auth/register": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Register new user for external application like mobile",
        "operationId": "Auth_Register"
      }
    },
    "/api/v5/partners/{partnerId}/rfids/{rfid}": {
      "get": {
        "tags": [
          "Partner"
        ],
        "summary": "Get RFID for partner",
        "operationId": "Partner_GetRfid",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/partners/{partnerId}/rfids": {
      "get": {
        "tags": [
          "Partner"
        ],
        "summary": "Get RFID tags for partner",
        "operationId": "Partner_GetRfidAll",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Partner"
        ],
        "summary": "Create RFID for partner, not connected to organisation",
        "description": "RFID hexadecimal is used in the transfer encoding Base16, in which each byte of the plaintext is broken into two 4-bit values and represented by two hexadecimal digits.",
        "operationId": "Partner_CreateRfid",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/partners/{partnerId}/rfids/{rfid}/revoke": {
      "put": {
        "tags": [
          "Partner"
        ],
        "summary": "Revoke specific RFID for partner",
        "operationId": "Partner_RevokeRfid",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/users/{userId}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get logged in user's details",
        "operationId": "User_Get",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/status": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Get charge point and it's connectors status. Note that measurement is only set if the connector is in charging mode.",
        "operationId": "ChargePoint_GetStatus",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/callbacks/enable": {
      "put": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Enable callback on chargepoints",
        "operationId": "ChargePoint_Enable",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/callbacks/disable": {
      "put": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Disable callback on chargepoints",
        "operationId": "ChargePoint_Disable",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/owned": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Get owned chargepoints",
        "operationId": "ChargePoint_GetAll",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/reboot": {
      "put": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Boot chargepoint",
        "operationId": "ChargePoint_Boot",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/register": {
      "put": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Register chargepoint to auth user",
        "operationId": "ChargePoint_Register",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/unregister": {
      "put": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Unregister chargepoint from user if any",
        "operationId": "ChargePoint_Unregister",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Get chargepoint. Expands with settings for charge point and connectors if query parameter expand=settings is applied.",
        "operationId": "ChargePoint_Get",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/settings": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Get chargepoint's settings",
        "operationId": "ChargePoint_GetSettings",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Update chargepoint's settings",
        "operationId": "ChargePoint_UpdateSettings",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/chargingsessions": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Get chargepoint's charging sessions. All parameters are optional, but in order to limit the number of resulting sessions,\nit is recommended that at least one parameter is set.",
        "operationId": "ChargePoint_GetChargingSessions",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/chargingsessions/{chargingSessionId}": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Get connector's charging session",
        "operationId": "ChargePoint_GetChargingSession",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/connectors/{connectorId}/chargingsessions": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Get connector's charging sessions. All parameters are optional, but in order to limit the number of resulting sessions,\nit is recommended that at least one parameter is set.",
        "operationId": "ChargePoint_GetChargingSessions2",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/connectors/{connectorId}/settings": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Get connector's settings",
        "operationId": "ChargePoint_GetConnectorSettings",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Update connector's settings",
        "operationId": "ChargePoint_UpdateConnectorSettings",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/partner": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Get partner for charge point",
        "operationId": "ChargePoint_GetPartner",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/connectors/{connectorId}/remotestart": {
      "put": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Remote start chargepoint. Only makes sense if rifdlock is on.",
        "operationId": "ChargePoint_RemoteStart",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/connectors/{connectorId}/remotestop": {
      "put": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Remote stop chargepoint. Only makes sense if rifdlock is on.",
        "operationId": "ChargePoint_RemoteStop",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/connectors/{connectorId}/schedule/override": {
      "put": {
        "tags": [
          "ChargePoint"
        ],
        "operationId": "ChargePoint_OverrideScheduleForOngoingChargingSession",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/schedule/override/status": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "operationId": "ChargePoint_GetScheduleOverrideStatus",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/schedules": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Get chargepoint's schedules. For CAPI chargers only.",
        "operationId": "ChargePoint_GetSchedules",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Update schedule. For CAPI chargers only.",
        "operationId": "ChargePoint_UpdateSchedule",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Creates schedule. For CAPI chargers only.",
        "operationId": "ChargePoint_CreateSchedule",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/chargepoints/{chargePointId}/schedules/{scheduleId}": {
      "get": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Get chargepoint's schedule. For CAPI chargers only.",
        "operationId": "ChargePoint_GetScheduleById",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ChargePoint"
        ],
        "summary": "Delete schedule. For CAPI chargers only.",
        "operationId": "ChargePoint_DeleteSchedule",
        "security": [
          {
            "JWT": [
              "Private",
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/organisations/{organisationId}/chargepoints/statuses": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get organisation's charge point and it's connectors status. Note that measurement is only set if the connector is in charging mode.",
        "operationId": "Organisation_GetChargePointsStatusesForOrganisation",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/organisations": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get organisations",
        "operationId": "Organisation_GetOrganisations",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/organisations/{organisationId}": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get organisation",
        "operationId": "Organisation_GetById",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/organisations/{organisationId}/chargepoints": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get organisation's chargepoints",
        "operationId": "Organisation_GetChargePointsForOrganisation",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/organisations/{organisationId}/chargingsessions": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get organisation's charging sessions",
        "operationId": "Organisation_GetChargingSessions",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/organisations/{organisationId}/users": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get users for organisation",
        "operationId": "Organisation_GetUsers",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Organisation"
        ],
        "summary": "Create user (and RFID tags if any). Note that password has to contain at least 8 characters.",
        "description": "RFID hexadecimal is used in the transfer encoding Base16, in which each byte of the plaintext is broken into two 4-bit values and represented by two hexadecimal digits.",
        "operationId": "Organisation_CreateUser",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/organisations/{organisationId}/users/{userId}": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get user for organisation",
        "operationId": "Organisation_GetUserById",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/organisations/{organisationId}/partner": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get partner for organisation",
        "operationId": "Organisation_GetPartner",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/organisations/{organisationId}/rfids": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get RFIDs for organisation",
        "operationId": "Organisation_GetRfids",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Organisation"
        ],
        "summary": "Create RFID",
        "description": "RFID hexadecimal is used in the transfer encoding Base16, in which each byte of the plaintext is broken into two 4-bit values and represented by two hexadecimal digits.",
        "operationId": "Organisation_CreateRfid",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/organisations/{organisationId}/rfids/{rfid}": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get RFID",
        "operationId": "Organisation_GetRfid",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    },
    "/api/v5/organisations/{organisationId}/rfids/{rfid}/revoke": {
      "put": {
        "tags": [
          "Organisation"
        ],
        "summary": "Revoke specific RFID for organisation",
        "operationId": "Organisation_RevokeRfid",
        "security": [
          {
            "JWT": [
              "Enterprise"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "JWT": {
        "type": "apiKey",
        "description": "Type into the text box: Bearer {your JWT token}.",
        "name": "Authorization",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "JWT": []
    }
  ]
}